# Copyright 2026 MinhTfresh. All Rights Reserved.
# Licensed under the Apache License, Version 2.0.
# Hardened AI Security Gateway & Container Sandbox Ecosystem by MinhTfresh

import os
import httpx

SLACK_WEBHOOK_URL = os.getenv("SLACK_SECURITY_WEBHOOK_URL", "")

def dispatch_incident_alarm(event_type: str, user_id: str, severity: str, details: dict):
    """
    Dispatches security incidents to Slack or logs them locally.
    
    Args:
        event_type: Type of security event (e.g., "PROMPT_INJECTION_ATTEMPT")
        user_id: ID of the user who triggered the event
        severity: Severity level (LOW, MEDIUM, HIGH, CRITICAL)
        details: Dictionary containing event details
    """
    if not SLACK_WEBHOOK_URL:
        print(f"[ALERT FALLBACK] [{severity}] {event_type} generated by {user_id}. Details: {details}")
        return
    
    slack_blocks = {
        "blocks": [
            {"type": "header", "text": {"type": "plain_text", "text": f"🚨 AI Security Incident: {event_type}"}},
            {"type": "section", "fields": [
                {"type": "mrkdwn", "text": f"*Severity:* {severity}"},
                {"type": "mrkdwn", "text": f"*User ID:* {user_id}"},
                {"type": "mrkdwn", "text": f"*Status:* INTERCEPTED & CONTAINED"}
            ]},
            {"type": "section", "text": {"type": "mrkdwn", "text": f"*Context Matrix:*\n\n```{httpx.utils.json_dumps(details, indent=2)}```"}}
        ]
    }
    
    try:
        httpx.post(SLACK_WEBHOOK_URL, json=slack_blocks, timeout=2.0)
    except Exception as e:
        print(f"Alert pipeline failure: {e}")
